---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com
spec:
  group: example.com
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  scope: Namespaced
  versions:
  - name: v1
    subresources: { status: {} }
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion: { type: string }
          kind: { type: string }
          metadata: { type: object }
          spec:
            type: object
            required: [foo]
            properties: { foo: { type: string }, bar: { type: string } }
          status: { type: object, properties: {} }
  - name: v2
    subresources: { status: {} }
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion: { type: string }
          kind: { type: string }
          metadata: { type: object }
          spec:
            type: object
            required: [foo]
            properties: { foo: { type: string }, bar: { type: string } }
          status: { type: object, properties: {} }
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bars.example.com
spec:
  group: example.com
  names:
    kind: Bar
    listKind: BarList
    plural: bars
    singular: bar
  scope: Namespaced
  versions:
  - name: v1
    subresources: { status: {} }
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion: { type: string }
          kind: { type: string }
          metadata: { type: object }
          spec:
            type: object
            required: [bar]
            properties: { baz: { type: string }, bar: { type: string } }
          status: { type: object, properties: {} }
