apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: foo
spec:
  dnsNames:
  - foo.example.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: production
  secretName: foo
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bar
  creationTimestamp: null
spec:
  dnsNames:
  - bar.example.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: production
  secretName: bar
